name: Update

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: 🔄 Sync version with upstream
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          update-script: |
            # Get release tags by naming convention: "dosbox-x-v{year.month.patch}"
            # as per https://github.com/joncampbell123/dosbox-x/commit/72be4229
            RELEASE_REGEX="^dosbox-x-v[0-9]{4}\.[0-9]{2}\.[0-9]+$"
            VERSION=$(
              curl -sL https://api.github.com/repos/joncampbell123/dosbox-x/releases |
              jq -r --arg str ${RELEASE_REGEX} '.[].tag_name | select(test($str))' |
              head -n1 | cut -d'v' -f2
            )
            sed -i 's/^\(version: \).*$/\1'"$VERSION"'/' snap/snapcraft.yaml
